apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: digits-fastapi-app-amd64
spec:
  template:
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/digits-454618/digits-fastapi-app-amd64/digits-fastapi-app-amd64:latest
          env:
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "4"
              memory: "4Gi"
            requests:
              cpu: "4"
              memory: "4Gi"