name: Test and Deploy API

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check code style with isort
      run: |
        isort --check-only --diff .

    - name: Check code style with black
      run: |
        black --check .

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t digits-fastapi-app

    - name: Run container
      run: |
        docker run -d -p 8080:8080 --name test-container digits-fastapi-app
        sleep 5  # Wait for the container to start

    - name: Run API tests
      run: |
        curl -X 'POST' 'http://127.0.0.1:8080/Predict' \
          -H 'accept: application/json' \
          -H 'Content-Type: multipart/form-data' \
          -F 'file=@./ml/concat_img/15aI4952.png'  ||  exit 1
        pytest test_api.py -v  ||  exit 1

    - name: Stop and remove container
      run: docker stop test-container && docker rm test-container
